### ISSUE TITLE
Custom Data Types

### ISSUE THREAD

**Issue by zbarge** [zbarge/zeex#54]
It would be cool to build in a lot of common formats and a settings file that would map a field to a custom data type. Then customize the fields_edit Dialog to show a ComboBoxDelegate with each custom data type available (on top of standard data types)

Then have a process for the mapper to check new data dtypes and apply their validation/standardization methods.

- [ ] Full Name
- [ ] First Name
- [ ] Last Name
- [ ] Address
- [ ] City
- [ ] State
- [ ] Zipcode
- [ ] Email Address (ListWise API?)
- [ ] Phone Number
- [ ] Currency
- [ ] Deduplicated Category (Check for fuzzy-matched duplicates and standardize)
- [ ] Latitude/Longitude
- [ ] Distance (Requires reference to Latitude, Longitude, & Source zip code)
- [ ] URL
